before_script:
- pwd
- export VERSION=latest
- export REPO=hieutrtr
- export PACKAGE=imaginary
- export DIST_NAME=imaginary

after_script:
- tree

stages:
- dockerize
- clean


# dockerize:
#   stage: dockerize
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker version
#     - docker build -t $CI_REGISTRY_IMAGE:latest .
#     # push only for tags
#     - "[[ -z $CI_BUILD_TAG ]] && exit 0"
#     - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#     - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
  - docker build -t registry.gitlab.com/$REPO/$DIST_NAME:$VERSION .
  - docker push registry.gitlab.com/$REPO/$DIST_NAME:$VERSION
  tags:
  - docker

test:
  stage: test
  script:
  - go test
  tags:
  - docker

clean:docker:
  stage: clean
  script:
  - docker images
  - docker rmi -f registry.gitlab.com/$REPO/$DIST_NAME:$VERSION
  tags:
  - docker
