before_script:
- pwd
- export VERSION=latest
- export REPO=hieutrtr
- export PACKAGE=imaginary
- export DIST_NAME=imaginary

stages:
- dockerize
- clean

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/$REPO/$DIST_NAME:$VERSION .
  - docker push registry.gitlab.com/$REPO/$DIST_NAME:$VERSION
  tags:
  - docker

clean:docker:
  stage: clean
  script:
  - docker images
  - docker rmi -f registry.gitlab.com/$REPO/$DIST_NAME:$VERSION
  tags:
  - docker
