image: docker:git
services:
- docker:dind

before_script:
- pwd
- export VERSION=latest
- export REPO=hieutrtr
- export PACKAGE=imaginary
- export DIST_NAME=imaginary

after_script:
- tree

stages:
- dockerize
- clean

dockerize:
  stage: dockerize
  script:
  - docker build -t registry.gitlab.com/$REPO/$DIST_NAME:$VERSION .
  - docker push registry.gitlab.com/$REPO/$DIST_NAME:$VERSION
  tags:
  - docker

test:
  stage: test
  script:
  - go test
  tags:
  - docker

clean:docker:
  stage: clean
  script:
  - docker images
  - docker rmi -f registry.gitlab.com/$REPO/$DIST_NAME:$VERSION
  tags:
  - docker
